# Generated by Django 3.2 on 2021-04-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': ('LevelDamage',),
                'verbose_name_plural': 'LevelDamage',
                'ordering': ['id'],
            },
        ),
    ]
