# Generated by Django 3.2 on 2021-04-25 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorydamage', '0001_initial'),
        ('typepainting', '0001_initial'),
        ('leveldamage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostRestauration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveBigIntegerField(default=1, help_text='Cost', verbose_name='Cost')),
                ('category_damage', models.ForeignKey(help_text='CategoryDamage', on_delete=django.db.models.deletion.DO_NOTHING, to='categorydamage.categorydamage', verbose_name='CategoryDamage')),
                ('level_damage', models.ForeignKey(help_text='LevelDamage', on_delete=django.db.models.deletion.DO_NOTHING, to='leveldamage.leveldamage', verbose_name='LevelDamage')),
                ('type_painting', models.ForeignKey(help_text='TypePainting', on_delete=django.db.models.deletion.DO_NOTHING, to='typepainting.typepainting', verbose_name='TypePainting')),
            ],
            options={
                'verbose_name': ('CostRestauration',),
                'verbose_name_plural': 'CostRestauration',
                'ordering': ['id'],
            },
        ),
    ]
