# Generated by Django 3.2 on 2021-04-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typepainting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typepainting',
            name='name_archive',
        ),
    ]
